/**
 * GL Transitions Registry
 * Maps normalized kebab-case names → transition metadata.
 * All 121 transitions from gl-transitions/gl-transitions.
 */

export const GL_TRANSITIONS = {
  // ─── No parameters ───────────────────────────────────────────────────────────
  'book-flip': {
    name: 'book-flip',
    displayName: { zh: '书本翻页', en: 'Book Flip' },
    glslFile: 'BookFlip.glsl',
    params: [],
    hasParams: false,
    sampler2D: false,
  },
  'bow-tie-horizontal': {
    name: 'bow-tie-horizontal',
    displayName: { zh: '水平蝴蝶结', en: 'Bow Tie Horizontal' },
    glslFile: 'BowTieHorizontal.glsl',
    params: [],
    hasParams: false,
    sampler2D: false,
  },
  'bow-tie-vertical': {
    name: 'bow-tie-vertical',
    displayName: { zh: '垂直蝴蝶结', en: 'Bow Tie Vertical' },
    glslFile: 'BowTieVertical.glsl',
    params: [],
    hasParams: false,
    sampler2D: false,
  },
  'cannabisleaf': {
    name: 'cannabisleaf',
    displayName: { zh: '绽放涟漪', en: 'Cannabisleaf' },
    glslFile: 'cannabisleaf.glsl',
    params: [],
    hasParams: false,
    sampler2D: false,
  },
  'coord-from-in': {
    name: 'coord-from-in',
    displayName: { zh: '坐标来源转场', en: 'Coord From In' },
    glslFile: 'coord-from-in.glsl',
    params: [],
    hasParams: false,
    sampler2D: false,
  },
  'crosswarp': {
    name: 'crosswarp',
    displayName: { zh: '交叉扭曲', en: 'Crosswarp' },
    glslFile: 'crosswarp.glsl',
    params: [],
    hasParams: false,
    sampler2D: false,
  },
  'dreamy': {
    name: 'dreamy',
    displayName: { zh: '梦幻转场', en: 'Dreamy' },
    glslFile: 'Dreamy.glsl',
    params: [],
    hasParams: false,
    sampler2D: false,
  },
  'fade': {
    name: 'fade',
    displayName: { zh: '淡入淡出', en: 'Fade' },
    glslFile: 'fade.glsl',
    params: [],
    hasParams: false,
    sampler2D: false,
  },
  'fold': {
    name: 'fold',
    displayName: { zh: '折叠转场', en: 'Fold' },
    glslFile: 'Fold.glsl',
    params: [],
    hasParams: false,
    sampler2D: false,
  },
  'fragment': {
    name: 'fragment',
    displayName: { zh: '碎片转场', en: 'Fragment' },
    glslFile: 'fragment.glsl',
    params: [],
    hasParams: false,
    sampler2D: false,
  },
  'glitch-displace': {
    name: 'glitch-displace',
    displayName: { zh: '故障位移', en: 'Glitch Displace' },
    glslFile: 'GlitchDisplace.glsl',
    params: [],
    hasParams: false,
    sampler2D: false,
  },
  'glitch-memories': {
    name: 'glitch-memories',
    displayName: { zh: '故障记忆', en: 'Glitch Memories' },
    glslFile: 'GlitchMemories.glsl',
    params: [],
    hasParams: false,
    sampler2D: false,
  },
  'heart': {
    name: 'heart',
    displayName: { zh: '心形转场', en: 'Heart' },
    glslFile: 'heart.glsl',
    params: [],
    hasParams: false,
    sampler2D: false,
  },
  'hsvfade': {
    name: 'hsvfade',
    displayName: { zh: 'HSV淡入', en: 'HSV Fade' },
    glslFile: 'HSVfade.glsl',
    params: [],
    hasParams: false,
    sampler2D: false,
  },
  'horizontal-close': {
    name: 'horizontal-close',
    displayName: { zh: '水平关闭', en: 'Horizontal Close' },
    glslFile: 'HorizontalClose.glsl',
    params: [],
    hasParams: false,
    sampler2D: false,
  },
  'horizontal-open': {
    name: 'horizontal-open',
    displayName: { zh: '水平打开', en: 'Horizontal Open' },
    glslFile: 'HorizontalOpen.glsl',
    params: [],
    hasParams: false,
    sampler2D: false,
  },
  'inverted-page-curl': {
    name: 'inverted-page-curl',
    displayName: { zh: '反向翻页', en: 'Inverted Page Curl' },
    glslFile: 'InvertedPageCurl.glsl',
    params: [],
    hasParams: false,
    sampler2D: false,
  },
  'left-right': {
    name: 'left-right',
    displayName: { zh: '左右转场', en: 'Left Right' },
    glslFile: 'LeftRight.glsl',
    params: [],
    hasParams: false,
    sampler2D: false,
  },
  'multiply-blend': {
    name: 'multiply-blend',
    displayName: { zh: '正片叠底', en: 'Multiply Blend' },
    glslFile: 'multiply_blend.glsl',
    params: [],
    hasParams: false,
    sampler2D: false,
  },
  'randomnoisex': {
    name: 'randomnoisex',
    displayName: { zh: '随机噪声X', en: 'Random Noise X' },
    glslFile: 'randomNoisex.glsl',
    params: [],
    hasParams: false,
    sampler2D: false,
  },
  'rotate-transition': {
    name: 'rotate-transition',
    displayName: { zh: '旋转转场', en: 'Rotate Transition' },
    glslFile: 'rotateTransition.glsl',
    params: [],
    hasParams: false,
    sampler2D: false,
  },
  'scale-in': {
    name: 'scale-in',
    displayName: { zh: '缩入转场', en: 'Scale In' },
    glslFile: 'scale-in.glsl',
    params: [],
    hasParams: false,
    sampler2D: false,
  },
  'simple-flip': {
    name: 'simple-flip',
    displayName: { zh: '简单翻转', en: 'Simple Flip' },
    glslFile: 'SimpleFlip.glsl',
    params: [],
    hasParams: false,
    sampler2D: false,
  },
  'swirl': {
    name: 'swirl',
    displayName: { zh: '漩涡转场', en: 'Swirl' },
    glslFile: 'Swirl.glsl',
    params: [],
    hasParams: false,
    sampler2D: false,
  },
  'tangent-motion-blur': {
    name: 'tangent-motion-blur',
    displayName: { zh: '正切运动模糊', en: 'Tangent Motion Blur' },
    glslFile: 'tangentMotionBlur.glsl',
    params: [],
    hasParams: false,
    sampler2D: false,
  },
  'top-bottom': {
    name: 'top-bottom',
    displayName: { zh: '上下转场', en: 'Top Bottom' },
    glslFile: 'TopBottom.glsl',
    params: [],
    hasParams: false,
    sampler2D: false,
  },
  'vertical-close': {
    name: 'vertical-close',
    displayName: { zh: '垂直关闭', en: 'Vertical Close' },
    glslFile: 'VerticalClose.glsl',
    params: [],
    hasParams: false,
    sampler2D: false,
  },
  'vertical-open': {
    name: 'vertical-open',
    displayName: { zh: '垂直打开', en: 'Vertical Open' },
    glslFile: 'VerticalOpen.glsl',
    params: [],
    hasParams: false,
    sampler2D: false,
  },
  'windowblinds': {
    name: 'windowblinds',
    displayName: { zh: '百叶窗转场', en: 'Window Blinds' },
    glslFile: 'windowblinds.glsl',
    params: [],
    hasParams: false,
    sampler2D: false,
  },
  'wipe-down': {
    name: 'wipe-down',
    displayName: { zh: '向下擦除', en: 'Wipe Down' },
    glslFile: 'wipeDown.glsl',
    params: [],
    hasParams: false,
    sampler2D: false,
  },
  'wipe-left': {
    name: 'wipe-left',
    displayName: { zh: '向左擦除', en: 'Wipe Left' },
    glslFile: 'wipeLeft.glsl',
    params: [],
    hasParams: false,
    sampler2D: false,
  },
  'wipe-right': {
    name: 'wipe-right',
    displayName: { zh: '向右擦除', en: 'Wipe Right' },
    glslFile: 'wipeRight.glsl',
    params: [],
    hasParams: false,
    sampler2D: false,
  },
  'wipe-up': {
    name: 'wipe-up',
    displayName: { zh: '向上擦除', en: 'Wipe Up' },
    glslFile: 'wipeUp.glsl',
    params: [],
    hasParams: false,
    sampler2D: false,
  },
  'x-axis-translation': {
    name: 'x-axis-translation',
    displayName: { zh: 'X轴平移', en: 'X Axis Translation' },
    glslFile: 'x_axis_translation.glsl',
    params: [],
    hasParams: false,
    sampler2D: false,
  },
  'zoom-in-circles': {
    name: 'zoom-in-circles',
    displayName: { zh: '圆形缩小', en: 'Zoom In Circles' },
    glslFile: 'ZoomInCircles.glsl',
    params: [],
    hasParams: false,
    sampler2D: false,
  },
  'zoom-in-out': {
    name: 'zoom-in-out',
    displayName: { zh: '缩入缩出', en: 'Zoom In Out' },
    glslFile: 'zoomInOut.glsl',
    params: [],
    hasParams: false,
    sampler2D: false,
  },

  // ─── With parameters ────────────────────────────────────────────────────────
  'advanced-mosaic': {
    name: 'advanced-mosaic',
    displayName: { zh: '高级马赛克', en: 'Advanced Mosaic' },
    glslFile: 'AdvancedMosaic.glsl',
    params: [{ name: 'pixelSize', type: 'float', default: 50.0 }],
    hasParams: true,
    sampler2D: false,
  },
  'angular': {
    name: 'angular',
    displayName: { zh: '角度转场', en: 'Angular' },
    glslFile: 'angular.glsl',
    params: [{ name: 'startingAngle', type: 'float', default: 90.0 }],
    hasParams: true,
    sampler2D: false,
  },
  'block-dissolve': {
    name: 'block-dissolve',
    displayName: { zh: '块状消散', en: 'Block Dissolve' },
    glslFile: 'BlockDissolve.glsl',
    params: [{ name: 'blocksize', type: 'float', default: 0.02 }],
    hasParams: true,
    sampler2D: false,
  },
  'bounce': {
    name: 'bounce',
    displayName: { zh: '弹跳转场', en: 'Bounce' },
    glslFile: 'Bounce.glsl',
    params: [
      { name: 'shadow_colour', type: 'vec4', default: [0, 0, 0, 0.6] },
      { name: 'shadow_height', type: 'float', default: 0.075 },
      { name: 'bounces', type: 'float', default: 3.0 },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'bow-tie-with-parameter': {
    name: 'bow-tie-with-parameter',
    displayName: { zh: '参数化蝴蝶结', en: 'Bow Tie With Parameter' },
    glslFile: 'BowTieWithParameter.glsl',
    params: [
      { name: 'adjust', type: 'float', default: 0.5 },
      { name: 'reverse', type: 'bool', default: false },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'box': {
    name: 'box',
    displayName: { zh: '盒状转场', en: 'Box' },
    glslFile: 'Box.glsl',
    params: [
      { name: 'rectIn', type: 'int', default: 1 },
      { name: 'location', type: 'int', default: 0 },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'burn': {
    name: 'burn',
    displayName: { zh: '燃烧转场', en: 'Burn' },
    glslFile: 'burn.glsl',
    params: [{ name: 'color', type: 'vec3', default: [0.9, 0.4, 0.2] }],
    hasParams: true,
    sampler2D: false,
  },
  'burn0': {
    name: 'burn0',
    displayName: { zh: '燃烧淡化', en: 'Burn 0' },
    glslFile: 'burn0.glsl',
    params: [{ name: 'burnColor', type: 'vec3', default: [1.0, 0.5, 0.0] }],
    hasParams: true,
    sampler2D: false,
  },
  'butterfly-wave-scrawler': {
    name: 'butterfly-wave-scrawler',
    displayName: { zh: '蝴蝶波浪', en: 'Butterfly Wave Scrawler' },
    glslFile: 'ButterflyWaveScrawler.glsl',
    params: [
      { name: 'amplitude', type: 'float', default: 1.0 },
      { name: 'waves', type: 'float', default: 30.0 },
      { name: 'colorSeparation', type: 'float', default: 0.3 },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'chessboard': {
    name: 'chessboard',
    displayName: { zh: '棋盘格转场', en: 'Chessboard' },
    glslFile: 'chessboard.glsl',
    params: [{ name: 'grid_num', type: 'float', default: 10.0 }],
    hasParams: true,
    sampler2D: false,
  },
  'circle': {
    name: 'circle',
    displayName: { zh: '圆形转场', en: 'Circle' },
    glslFile: 'circle.glsl',
    params: [
      { name: 'center', type: 'vec2', default: [0.5, 0.5] },
      { name: 'backColor', type: 'vec3', default: [0.1, 0.1, 0.1] },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'circle-crop': {
    name: 'circle-crop',
    displayName: { zh: '圆形裁剪转场', en: 'Circle Crop' },
    glslFile: 'CircleCrop.glsl',
    params: [{ name: 'bgcolor', type: 'vec4', default: [0, 0, 0, 1.0] }],
    hasParams: true,
    sampler2D: false,
  },
  'circleopen': {
    name: 'circleopen',
    displayName: { zh: '圆形展开', en: 'Circle Open' },
    glslFile: 'circleopen.glsl',
    params: [
      { name: 'smoothness', type: 'float', default: 0.3 },
      { name: 'opening', type: 'bool', default: true },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'colour-distance': {
    name: 'colour-distance',
    displayName: { zh: '颜色距离', en: 'Colour Distance' },
    glslFile: 'ColourDistance.glsl',
    params: [{ name: 'power', type: 'float', default: 5.0 }],
    hasParams: true,
    sampler2D: false,
  },
  'colorphase': {
    name: 'colorphase',
    displayName: { zh: '相位颜色', en: 'Color Phase' },
    glslFile: 'colorphase.glsl',
    params: [
      { name: 'fromStep', type: 'vec4', default: [0, 0.2, 0.4, 0] },
      { name: 'toStep', type: 'vec4', default: [0.6, 0.8, 1, 1] },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'crazy-parametric-fun': {
    name: 'crazy-parametric-fun',
    displayName: { zh: '参数曲线', en: 'Crazy Parametric Fun' },
    glslFile: 'CrazyParametricFun.glsl',
    params: [
      { name: 'a', type: 'float', default: 4.0 },
      { name: 'b', type: 'float', default: 1.0 },
      { name: 'amplitude', type: 'float', default: 120.0 },
      { name: 'smoothness', type: 'float', default: 0.1 },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'crosshatch': {
    name: 'crosshatch',
    displayName: { zh: '十字阴影', en: 'Crosshatch' },
    glslFile: 'crosshatch.glsl',
    params: [
      { name: 'center', type: 'vec2', default: [0.5, 0.5] },
      { name: 'threshold', type: 'float', default: 3.0 },
      { name: 'fadeEdge', type: 'float', default: 0.1 },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'cross-zoom': {
    name: 'cross-zoom',
    displayName: { zh: '交叉缩放转场', en: 'Cross Zoom' },
    glslFile: 'CrossZoom.glsl',
    params: [{ name: 'strength', type: 'float', default: 0.4 }],
    hasParams: true,
    sampler2D: false,
  },
  'cube': {
    name: 'cube',
    displayName: { zh: '立方体旋转', en: 'Cube' },
    glslFile: 'cube.glsl',
    params: [
      { name: 'persp', type: 'float', default: 0.7 },
      { name: 'unzoom', type: 'float', default: 0.3 },
      { name: 'reflection', type: 'float', default: 0.4 },
      { name: 'floating', type: 'float', default: 3.0 },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'defocus-blur': {
    name: 'defocus-blur',
    displayName: { zh: '散焦模糊', en: 'Defocus Blur' },
    glslFile: 'DefocusBlur.glsl',
    params: [{ name: 'blurSize', type: 'float', default: 0.02 }],
    hasParams: true,
    sampler2D: false,
  },
  'directional': {
    name: 'directional',
    displayName: { zh: '方向性转场', en: 'Directional' },
    glslFile: 'Directional.glsl',
    params: [{ name: 'direction', type: 'vec2', default: [0.0, 1.0] }],
    hasParams: true,
    sampler2D: false,
  },
  'directional-easing': {
    name: 'directional-easing',
    displayName: { zh: '方向缓动', en: 'Directional Easing' },
    glslFile: 'directional-easing.glsl',
    params: [{ name: 'direction', type: 'vec2', default: [0.0, 1.0] }],
    hasParams: true,
    sampler2D: false,
  },
  'directional-scaled': {
    name: 'directional-scaled',
    displayName: { zh: '方向缩放', en: 'Directional Scaled' },
    glslFile: 'DirectionalScaled.glsl',
    params: [
      { name: 'direction', type: 'vec2', default: [0.0, 1.0] },
      { name: 'scale', type: 'float', default: 0.7 },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'directionalwarp': {
    name: 'directionalwarp',
    displayName: { zh: '方向弯曲', en: 'Directional Warp' },
    glslFile: 'directionalwarp.glsl',
    params: [
      { name: 'smoothness', type: 'float', default: 0.1 },
      { name: 'direction', type: 'vec2', default: [-1.0, 1.0] },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'directionalwipe': {
    name: 'directionalwipe',
    displayName: { zh: '方向擦除', en: 'Directional Wipe' },
    glslFile: 'directionalwipe.glsl',
    params: [
      { name: 'direction', type: 'vec2', default: [1.0, -1.0] },
      { name: 'smoothness', type: 'float', default: 0.5 },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'displacement': {
    name: 'displacement',
    displayName: { zh: '置换转场', en: 'Displacement' },
    glslFile: 'displacement.glsl',
    params: [
      { name: 'displacementMap', type: 'sampler2D', default: '__default_noise__' },
      { name: 'strength', type: 'float', default: 0.5 },
    ],
    hasParams: true,
    sampler2D: true,
  },
  'dissolve': {
    name: 'dissolve',
    displayName: { zh: '溶解转场', en: 'Dissolve' },
    glslFile: 'dissolve.glsl',
    params: [
      { name: 'uLineWidth', type: 'float', default: 0.1 },
      { name: 'uSpreadClr', type: 'vec3', default: [1.0, 0.0, 0.0] },
      { name: 'uHotClr', type: 'vec3', default: [0.9, 0.9, 0.2] },
      { name: 'uPow', type: 'float', default: 5.0 },
      { name: 'uIntensity', type: 'float', default: 1.0 },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'doom-screen-transition': {
    name: 'doom-screen-transition',
    displayName: { zh: '毁灭屏幕', en: 'Doom Screen Transition' },
    glslFile: 'DoomScreenTransition.glsl',
    params: [
      { name: 'bars', type: 'int', default: 30 },
      { name: 'amplitude', type: 'float', default: 2.0 },
      { name: 'noise', type: 'float', default: 0.1 },
      { name: 'frequency', type: 'float', default: 0.5 },
      { name: 'dripScale', type: 'float', default: 0.5 },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'doorway': {
    name: 'doorway',
    displayName: { zh: '门洞转场', en: 'Doorway' },
    glslFile: 'doorway.glsl',
    params: [
      { name: 'reflection', type: 'float', default: 0.4 },
      { name: 'perspective', type: 'float', default: 0.4 },
      { name: 'depth', type: 'float', default: 3.0 },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'dreamy-zoom': {
    name: 'dreamy-zoom',
    displayName: { zh: '梦幻缩放', en: 'Dreamy Zoom' },
    glslFile: 'DreamyZoom.glsl',
    params: [
      { name: 'rotation', type: 'float', default: 6.0 },
      { name: 'scale', type: 'float', default: 1.2 },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'edge-transition': {
    name: 'edge-transition',
    displayName: { zh: '边缘转场', en: 'Edge Transition' },
    glslFile: 'EdgeTransition.glsl',
    params: [
      { name: 'edge_thickness', type: 'float', default: 0.001 },
      { name: 'edge_brightness', type: 'float', default: 8.0 },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'fadecolor': {
    name: 'fadecolor',
    displayName: { zh: '颜色淡化', en: 'Fade Color' },
    glslFile: 'fadecolor.glsl',
    params: [
      { name: 'color', type: 'vec3', default: [0, 0, 0] },
      { name: 'colorPhase', type: 'float', default: 0.4 },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'fadegrayscale': {
    name: 'fadegrayscale',
    displayName: { zh: '灰度淡化', en: 'Fade Grayscale' },
    glslFile: 'fadegrayscale.glsl',
    params: [{ name: 'intensity', type: 'float', default: 0.3 }],
    hasParams: true,
    sampler2D: false,
  },
  'film-burn': {
    name: 'film-burn',
    displayName: { zh: '胶片燃烧', en: 'Film Burn' },
    glslFile: 'FilmBurn.glsl',
    params: [{ name: 'seed', type: 'float', default: 2.31 }],
    hasParams: true,
    sampler2D: false,
  },
  'flyeye': {
    name: 'flyeye',
    displayName: { zh: '苍蝇眼转场', en: 'Fly Eye' },
    glslFile: 'flyeye.glsl',
    params: [
      { name: 'size', type: 'float', default: 0.04 },
      { name: 'zoom', type: 'float', default: 50.0 },
      { name: 'colorSeparation', type: 'float', default: 0.3 },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'grid-flip': {
    name: 'grid-flip',
    displayName: { zh: '网格翻转', en: 'Grid Flip' },
    glslFile: 'GridFlip.glsl',
    params: [
      { name: 'size', type: 'ivec2', default: [4, 4] },
      { name: 'pause', type: 'float', default: 0.1 },
      { name: 'dividerWidth', type: 'float', default: 0.05 },
      { name: 'bgcolor', type: 'vec4', default: [0, 0, 0, 1] },
      { name: 'randomness', type: 'float', default: 0.1 },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'hexagonalize': {
    name: 'hexagonalize',
    displayName: { zh: '六边形化', en: 'Hexagonalize' },
    glslFile: 'hexagonalize.glsl',
    params: [
      { name: 'steps', type: 'int', default: 50 },
      { name: 'horizontalHexagons', type: 'float', default: 20.0 },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'kaleidoscope': {
    name: 'kaleidoscope',
    displayName: { zh: '万花筒', en: 'Kaleidoscope' },
    glslFile: 'kaleidoscope.glsl',
    params: [
      { name: 'speed', type: 'float', default: 1.0 },
      { name: 'angle', type: 'float', default: 1.0 },
      { name: 'power', type: 'float', default: 1.5 },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'linear-blur': {
    name: 'linear-blur',
    displayName: { zh: '线性模糊', en: 'Linear Blur' },
    glslFile: 'LinearBlur.glsl',
    params: [{ name: 'intensity', type: 'float', default: 0.1 }],
    hasParams: true,
    sampler2D: false,
  },
  'luma': {
    name: 'luma',
    displayName: { zh: '亮度转场', en: 'Luma' },
    glslFile: 'luma.glsl',
    params: [{ name: 'luma', type: 'sampler2D', default: '__default_noise__' }],
    hasParams: true,
    sampler2D: true,
  },
  'luminance-melt': {
    name: 'luminance-melt',
    displayName: { zh: '亮度融化', en: 'Luminance Melt' },
    glslFile: 'luminance_melt.glsl',
    params: [
      { name: 'direction', type: 'bool', default: true },
      { name: 'l_threshold', type: 'float', default: 0.8 },
      { name: 'above', type: 'bool', default: false },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'morph': {
    name: 'morph',
    displayName: { zh: '变形转场', en: 'Morph' },
    glslFile: 'morph.glsl',
    params: [{ name: 'strength', type: 'float', default: 0.1 }],
    hasParams: true,
    sampler2D: false,
  },
  'mosaic': {
    name: 'mosaic',
    displayName: { zh: '马赛克转场', en: 'Mosaic' },
    glslFile: 'Mosaic.glsl',
    params: [
      { name: 'endx', type: 'int', default: 2 },
      { name: 'endy', type: 'int', default: -1 },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'mosaic-transition': {
    name: 'mosaic-transition',
    displayName: { zh: '马赛克转场2', en: 'Mosaic Transition' },
    glslFile: 'mosaic_transition.glsl',
    params: [{ name: 'mosaicNum', type: 'float', default: 10.0 }],
    hasParams: true,
    sampler2D: false,
  },
  'overexposure': {
    name: 'overexposure',
    displayName: { zh: '曝光过度', en: 'Overexposure' },
    glslFile: 'Overexposure.glsl',
    params: [{ name: 'strength', type: 'float', default: 0.6 }],
    hasParams: true,
    sampler2D: false,
  },
  'parametric-glitch': {
    name: 'parametric-glitch',
    displayName: { zh: '图形故障', en: 'Parametric Glitch' },
    glslFile: 'parametric_glitch.glsl',
    params: [
      { name: 'ampx', type: 'float', default: 1.0 },
      { name: 'ampy', type: 'float', default: 1.0 },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'perlin': {
    name: 'perlin',
    displayName: { zh: 'Perlin噪声', en: 'Perlin' },
    glslFile: 'perlin.glsl',
    params: [
      { name: 'scale', type: 'float', default: 4.0 },
      { name: 'smoothness', type: 'float', default: 0.01 },
      { name: 'seed', type: 'float', default: 12.9898 },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'pinwheel': {
    name: 'pinwheel',
    displayName: { zh: '风车转场', en: 'Pinwheel' },
    glslFile: 'pinwheel.glsl',
    params: [{ name: 'speed', type: 'float', default: 2.0 }],
    hasParams: true,
    sampler2D: false,
  },
  'pixelize': {
    name: 'pixelize',
    displayName: { zh: '像素化转场', en: 'Pixelize' },
    glslFile: 'pixelize.glsl',
    params: [
      { name: 'squaresMin', type: 'ivec2', default: [20, 20] },
      { name: 'steps', type: 'int', default: 50 },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'polar-function': {
    name: 'polar-function',
    displayName: { zh: '极坐标函数', en: 'Polar Function' },
    glslFile: 'polar_function.glsl',
    params: [{ name: 'segments', type: 'int', default: 5 }],
    hasParams: true,
    sampler2D: false,
  },
  'polka-dots-curtain': {
    name: 'polka-dots-curtain',
    displayName: { zh: '波尔卡点幕布', en: 'Polka Dots Curtain' },
    glslFile: 'PolkaDotsCurtain.glsl',
    params: [
      { name: 'dots', type: 'float', default: 20.0 },
      { name: 'center', type: 'vec2', default: [0, 0] },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'power-kaleido': {
    name: 'power-kaleido',
    displayName: { zh: '指数万花筒', en: 'Power Kaleido' },
    glslFile: 'powerKaleido.glsl',
    params: [
      { name: 'scale', type: 'float', default: 2.0 },
      { name: 'z', type: 'float', default: 1.5 },
      { name: 'speed', type: 'float', default: 5.0 },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'puzzle-right': {
    name: 'puzzle-right',
    displayName: { zh: '拼图向右', en: 'Puzzle Right' },
    glslFile: 'PuzzleRight.glsl',
    params: [
      { name: 'size', type: 'ivec2', default: [4, 4] },
      { name: 'pause', type: 'float', default: 0.1 },
      { name: 'dividerWidth', type: 'float', default: 0.005 },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'radial': {
    name: 'radial',
    displayName: { zh: '径向转场', en: 'Radial' },
    glslFile: 'Radial.glsl',
    params: [{ name: 'smoothness', type: 'float', default: 1.0 }],
    hasParams: true,
    sampler2D: false,
  },
  'randomsquares': {
    name: 'randomsquares',
    displayName: { zh: '随机方块', en: 'Random Squares' },
    glslFile: 'randomsquares.glsl',
    params: [
      { name: 'size', type: 'ivec2', default: [10, 10] },
      { name: 'smoothness', type: 'float', default: 0.5 },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'rectangle': {
    name: 'rectangle',
    displayName: { zh: '矩形转场', en: 'Rectangle' },
    glslFile: 'Rectangle.glsl',
    params: [{ name: 'bgcolor', type: 'vec4', default: [0, 0, 0, 1.0] }],
    hasParams: true,
    sampler2D: false,
  },
  'rectangle-crop': {
    name: 'rectangle-crop',
    displayName: { zh: '矩形裁剪', en: 'Rectangle Crop' },
    glslFile: 'RectangleCrop.glsl',
    params: [{ name: 'bgcolor', type: 'vec4', default: [0, 0, 0, 1.0] }],
    hasParams: true,
    sampler2D: false,
  },
  'ripple': {
    name: 'ripple',
    displayName: { zh: '波纹转场', en: 'Ripple' },
    glslFile: 'ripple.glsl',
    params: [
      { name: 'amplitude', type: 'float', default: 100.0 },
      { name: 'speed', type: 'float', default: 50.0 },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'rolls': {
    name: 'rolls',
    displayName: { zh: '卷曲转场', en: 'Rolls' },
    glslFile: 'Rolls.glsl',
    params: [
      { name: 'type', type: 'int', default: 0 },
      { name: 'rotDown', type: 'bool', default: false },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'rotate-scale-fade': {
    name: 'rotate-scale-fade',
    displayName: { zh: '旋转缩放淡化', en: 'Rotate Scale Fade' },
    glslFile: 'rotate_scale_fade.glsl',
    params: [
      { name: 'center', type: 'vec2', default: [0.5, 0.5] },
      { name: 'rotations', type: 'float', default: 1.0 },
      { name: 'scale', type: 'float', default: 8.0 },
      { name: 'backColor', type: 'vec4', default: [0.15, 0.15, 0.15, 1.0] },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'rotate-scale-vanish': {
    name: 'rotate-scale-vanish',
    displayName: { zh: '旋转缩放消失', en: 'Rotate Scale Vanish' },
    glslFile: 'RotateScaleVanish.glsl',
    params: [
      { name: 'fadeInSecond', type: 'bool', default: true },
      { name: 'reverseEffect', type: 'bool', default: false },
      { name: 'reverseRotation', type: 'bool', default: false },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'simple-zoom': {
    name: 'simple-zoom',
    displayName: { zh: '简单缩放', en: 'Simple Zoom' },
    glslFile: 'SimpleZoom.glsl',
    params: [{ name: 'zoom_quickness', type: 'float', default: 0.8 }],
    hasParams: true,
    sampler2D: false,
  },
  'simple-zoom-out': {
    name: 'simple-zoom-out',
    displayName: { zh: '简单缩小', en: 'Simple Zoom Out' },
    glslFile: 'SimpleZoomOut.glsl',
    params: [
      { name: 'zoom_quickness', type: 'float', default: 0.8 },
      { name: 'fade', type: 'bool', default: true },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'slides': {
    name: 'slides',
    displayName: { zh: '幻灯片转场', en: 'Slides' },
    glslFile: 'Slides.glsl',
    params: [
      { name: 'type', type: 'int', default: 0 },
      { name: 'in', type: 'bool', default: false },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'split-slide-in-horizontal': {
    name: 'split-slide-in-horizontal',
    displayName: { zh: '水平滑入', en: 'Split Slide In Horizontal' },
    glslFile: 'splitSlideInHorizontal.glsl',
    params: [{ name: 'reverse', type: 'bool', default: false }],
    hasParams: true,
    sampler2D: false,
  },
  'split-slide-in-out-horizontal': {
    name: 'split-slide-in-out-horizontal',
    displayName: { zh: '水平滑入滑出', en: 'Split Slide In Out Horizontal' },
    glslFile: 'splitSlideInOutHorizontal.glsl',
    params: [{ name: 'reverse', type: 'bool', default: false }],
    hasParams: true,
    sampler2D: false,
  },
  'split-slide-in-out-vertical': {
    name: 'split-slide-in-out-vertical',
    displayName: { zh: '垂直滑入滑出', en: 'Split Slide In Out Vertical' },
    glslFile: 'splitSlideInOutVertical.glsl',
    params: [{ name: 'reverse', type: 'bool', default: false }],
    hasParams: true,
    sampler2D: false,
  },
  'split-slide-in-vertical': {
    name: 'split-slide-in-vertical',
    displayName: { zh: '垂直滑入', en: 'Split Slide In Vertical' },
    glslFile: 'splitSlideInVertical.glsl',
    params: [{ name: 'reverse', type: 'bool', default: false }],
    hasParams: true,
    sampler2D: false,
  },
  'split-slide-out-horizontal': {
    name: 'split-slide-out-horizontal',
    displayName: { zh: '水平滑出', en: 'Split Slide Out Horizontal' },
    glslFile: 'splitSlideOutHorizontal.glsl',
    params: [{ name: 'reverse', type: 'bool', default: false }],
    hasParams: true,
    sampler2D: false,
  },
  'split-slide-out-vertical': {
    name: 'split-slide-out-vertical',
    displayName: { zh: '垂直滑出', en: 'Split Slide Out Vertical' },
    glslFile: 'splitSlideOutVertical.glsl',
    params: [{ name: 'reverse', type: 'bool', default: false }],
    hasParams: true,
    sampler2D: false,
  },
  'squareswire': {
    name: 'squareswire',
    displayName: { zh: '方格线转场', en: 'Squares Wire' },
    glslFile: 'squareswire.glsl',
    params: [
      { name: 'squares', type: 'ivec2', default: [10, 10] },
      { name: 'direction', type: 'vec2', default: [1.0, -0.5] },
      { name: 'smoothness', type: 'float', default: 1.6 },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'squeeze': {
    name: 'squeeze',
    displayName: { zh: '挤压转场', en: 'Squeeze' },
    glslFile: 'squeeze.glsl',
    params: [{ name: 'colorSeparation', type: 'float', default: 0.04 }],
    hasParams: true,
    sampler2D: false,
  },
  'star-wipe': {
    name: 'star-wipe',
    displayName: { zh: '星形擦除', en: 'Star Wipe' },
    glslFile: 'StarWipe.glsl',
    params: [
      { name: 'border_thickness', type: 'float', default: 0.01 },
      { name: 'star_rotation', type: 'float', default: 0.75 },
      { name: 'border_color', type: 'vec4', default: [1, 1, 1, 1] },
      { name: 'star_center', type: 'vec2', default: [0.5, 0.5] },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'static-wipe': {
    name: 'static-wipe',
    displayName: { zh: '静态擦除', en: 'Static Wipe' },
    glslFile: 'static_wipe.glsl',
    params: [
      { name: 'u_transitionUpToDown', type: 'bool', default: true },
      { name: 'u_max_static_span', type: 'float', default: 0.5 },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'static-fade': {
    name: 'static-fade',
    displayName: { zh: '静态淡化', en: 'Static Fade' },
    glslFile: 'StaticFade.glsl',
    params: [
      { name: 'n_noise_pixels', type: 'float', default: 200.0 },
      { name: 'static_luminosity', type: 'float', default: 0.8 },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'stereo-viewer': {
    name: 'stereo-viewer',
    displayName: { zh: '立体视图', en: 'Stereo Viewer' },
    glslFile: 'StereoViewer.glsl',
    params: [
      { name: 'zoom', type: 'float', default: 0.88 },
      { name: 'corner_radius', type: 'float', default: 0.22 },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'swap': {
    name: 'swap',
    displayName: { zh: '交换转场', en: 'Swap' },
    glslFile: 'swap.glsl',
    params: [
      { name: 'reflection', type: 'float', default: 0.4 },
      { name: 'perspective', type: 'float', default: 0.2 },
      { name: 'depth', type: 'float', default: 3.0 },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'tiles-wave': {
    name: 'tiles-wave',
    displayName: { zh: '瓷砖波浪', en: 'Tiles Wave' },
    glslFile: 'TilesWave.glsl',
    params: [
      { name: 'tileCount', type: 'ivec2', default: [8, 8] },
      { name: 'flipX', type: 'bool', default: true },
      { name: 'flipY', type: 'bool', default: false },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'tv-static': {
    name: 'tv-static',
    displayName: { zh: '电视雪花', en: 'TV Static' },
    glslFile: 'TVStatic.glsl',
    params: [{ name: 'offset', type: 'float', default: 0.05 }],
    hasParams: true,
    sampler2D: false,
  },
  'undulating-burn-out': {
    name: 'undulating-burn-out',
    displayName: { zh: '波动燃烧', en: 'Undulating Burn Out' },
    glslFile: 'undulatingBurnOut.glsl',
    params: [
      { name: 'smoothness', type: 'float', default: 0.03 },
      { name: 'center', type: 'vec2', default: [0.5, 0.5] },
      { name: 'color', type: 'vec3', default: [0, 0, 0] },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'water-drop': {
    name: 'water-drop',
    displayName: { zh: '水滴转场', en: 'Water Drop' },
    glslFile: 'WaterDrop.glsl',
    params: [
      { name: 'amplitude', type: 'float', default: 30.0 },
      { name: 'speed', type: 'float', default: 30.0 },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'wind': {
    name: 'wind',
    displayName: { zh: '风力转场', en: 'Wind' },
    glslFile: 'wind.glsl',
    params: [
      { name: 'size', type: 'float', default: 0.2 },
      { name: 'reversed', type: 'bool', default: false },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'windowslice': {
    name: 'windowslice',
    displayName: { zh: '窗口切片', en: 'Window Slice' },
    glslFile: 'windowslice.glsl',
    params: [
      { name: 'count', type: 'float', default: 10.0 },
      { name: 'smoothness', type: 'float', default: 0.5 },
    ],
    hasParams: true,
    sampler2D: false,
  },
  'zoom-left-wipe': {
    name: 'zoom-left-wipe',
    displayName: { zh: '左侧缩放擦除', en: 'Zoom Left Wipe' },
    glslFile: 'ZoomLeftWipe.glsl',
    params: [{ name: 'zoom_quickness', type: 'float', default: 0.8 }],
    hasParams: true,
    sampler2D: false,
  },
  'zoom-right-wipe': {
    name: 'zoom-right-wipe',
    displayName: { zh: '右侧缩放擦除', en: 'Zoom Right Wipe' },
    glslFile: 'ZoomRigthWipe.glsl',
    params: [{ name: 'zoom_quickness', type: 'float', default: 0.8 }],
    hasParams: true,
    sampler2D: false,
  },
};

/**
 * Get a GL transition by its kebab-case name.
 * @param {string} name
 * @returns {typeof GL_TRANSITIONS[string] | null}
 */
export function getGLTransition(name) {
  return GL_TRANSITIONS[name] ?? null;
}

/**
 * List all GL transitions as an array.
 * @returns {Array<typeof GL_TRANSITIONS[string] & { name: string }>}
 */
export function listGLTransitions() {
  return Object.entries(GL_TRANSITIONS).map(([name, val]) => ({ name, ...val }));
}
